### ISSUE TITLE
Not updating server nor apps

### ISSUE THREAD

**Issue by Fgonzalez22** [SignalK/signalk-server#2021]
I have version 2.12.0 and it fails to update the server and apps. The server log reads:

Jun 25 16:48:10 stderr: /usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11 const pMap = require('p-map') ^ Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js not supported. Instead change the require of index.js in /usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules. at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11:14) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/cacache/lib/index.js:6:16) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:4:17) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:2:20) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:7:15) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:4:15) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:6:15) at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/replace-info.js:1:22) at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/error-message.js:4:21) at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exit-handler.js:5:22) at module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:15:23) at module.exports (/usr/lib/node_modules/npm/lib/es6/validate-engines.js:39:10) at module.exports (/usr/lib/node_modules/npm/lib/cli.js:4:31) at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:2:25) { code: 'ERR_REQUIRE_ESM' } Node.js v20.5.1

I don't understand much but it seems a compatibility problem of node.js

Any suggestions ?? Thanks :-)

**Comment by sbender9** [comment]
What version of nodejs are you running?

when did you run this? We just released a new version (2.14.1) that restores the ability to run with nodes v18 today.

**Comment by sbender9** [comment]
I just found an issue with that. I'm releasing v2.14.2. I'll let you know when it's ready...

**Comment by Fgonzalez22** [comment]
Hi, thanks. running Node.js v20.5.1
Last try today
Openplotter must have updated Node.Js i guess

**Comment by sbender9** [comment]
Some openplotter info here. https://github.com/SignalK/signalk-server/issues/1928

Please try with the latest server version 2.14.4

**Comment by Fgonzalez22** [comment]
I have tried the latest version and i still get an error:

Jun 26 14:50:28 stderr: /usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11 const pMap = require('p-map') ^ Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/lib/node_modules/npm/node_modules/cacache/node_modules/p-map/index.js from /usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js not supported. Instead change the require of index.js in /usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules. at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/cacache/lib/verify.js:11:14) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/cacache/lib/index.js:6:16) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:4:17) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:2:20) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:7:15) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js:4:15) at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/index.js:6:15) at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/replace-info.js:1:22) at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/error-message.js:4:21) at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exit-handler.js:5:22) at module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:15:23) at module.exports (/usr/lib/node_modules/npm/lib/es6/validate-engines.js:39:10) at module.exports (/usr/lib/node_modules/npm/lib/cli.js:4:31) at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:2:25) { code: 'ERR_REQUIRE_ESM' } 
Node.js v20.5.1

**Comment by tkurki** [comment]
I think your npm installationsis corrupt for some reason. Try reinstalling Node v22.

**Comment by Fgonzalez22** [comment]
aha, yes upgraded to node v22 and everything whent fine. Thanks Teppo!

**Comment by Fgonzalez22** [comment]
Hi Scott. I’m contacting you because im using signalk-sonoff-ewelink v2.0.1 (2025-07-02) on Signal K / Openplotter on a Raspi. 

Seems there is a problem with renewing the tokens. Apparently the APPID the plugin uses to identify to eWeLink is no longer valid.

 

Can you help me with any ideas…

 

Thanks in advance

 

 

Fernando González del Solar

**Comment by Fgonzalez22** [comment]
Hi Scott, hope you are well. 

 

We are having issues during the authentication for sonoff

 

To configure authentication, we go to [ <http://ewelink.scottbender.net:8000/login> http://ewelink.scottbender.net:8000/login] and enter our ewelink login information.

The resulting page looks like:

{

  "region": "us"

}

 

No token.

Hope you can help. Others have posted same issue

Thanks!! 

Best regards,

 

Fernando
